from CrossZeros.definition import FIELD_SIZE

DURATION_CONGRATULATION = 2
CELL_SIZE = 40
BUTTON_ZONE_SIZE = 60
WIDTH = FIELD_SIZE * CELL_SIZE
HEIGHT = WIDTH + BUTTON_ZONE_SIZE
FONT_NAME = 'arial'
TEXTS_FONT_SIZE = 32
FIGURE_FONT_SIZE = 38
LINE_WIDTH = 2
FIGURE_COLOR = (255, 255, 255)
FIELD_COLOR = (125, 125, 125)
CONGRATULATION_COLOR = (200, 200, 255)
COLOR_OF_BUTTONS_LABELS = (125, 125, 125)
BUTTONS_COLOR = (255, 255, 255)
CONGRATULATION_COORDINATES = (WIDTH // 2 - 95, BUTTON_ZONE_SIZE + WIDTH // 2 + 10)
ALIGNMENT_FIGURE_BY_X = 11
ALIGNMENT_FIGURE_BY_Y = 8
DEFLECTION_BUTTON = 10
ALIGNMENT_BUTTON_BY_X = 15
ALIGNMENT_BUTTON_BY_Y = -10


TEXTS = {
    'new game with cross': 'Начать игру, крестиками',
    'new game with zeros': 'Начать игру, ноликами',
    'congratulation': 'победил ',
}
